language: php
sudo: false
php:
  - 7.3
cache:
  directories:
    - "$HOME/.composer/cache/files"
env:
  - SYMFONY_VERSION="4.3.*" DB=mysql
script:
  - php bin/phpunit
services:
  - mysql
install:
  - cp .env.travis .env
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - mkdir -p config/jwt
  - openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:7834rhgi8uhgfuw834hr879329hr
  - openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:7834rhgi8uhgfuw834hr879329hr
